name = "wai-chat-bot"
main = "src/worker/index.ts"
compatibility_date = "2022-05-03"
compatibility_flags = ["durable_object_alarms"]

logpush = true
node_compat = true

[dev]
ip = "localhost"

[durable_objects]
bindings = [
    { name = "DO_WEBSOCKET", class_name = "WebSocketDurableObject" },
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["WebSocketDurableObject"] # Array of new classes

[[r2_buckets]]
# binding 的值 需要跟 [vars] / R2_STORAGE_BINGDING_KEY 一致
binding = 'STORAGE'
# 在 https://dash.cloudflare.com/ > R2 > Overview : Create bucket
bucket_name = 'wai-r2-prod'
preview_bucket_name="wai-r2-preview"

[[kv_namespaces]]
# binding 的值 需要跟 [vars] / KV_NAMESPACE_BINDING_KEY 一致
# 在 https://dash.cloudflare.com/ > Workers > KV : Create a namespace
binding = "DATABASE"
id = ""
preview_id = ""

[vars]
KV_NAMESPACE_BINDING_KEY="DATABASE"
R2_STORAGE_BINGDING_KEY="STORAGE"

IS_PROD = true
USER_ID_START = "20000000"
WAI_WORKER_API_TOKEN = ""
Access_Control_Allow_Origin = "*"
# 如果为空，则需要客户端传入apiKey
OPENAI_API_KEY = "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"
